name: compile

on:
  push:
    branches:
      - "[0-9]+-*"
  pull_request:
    branches: [ "dev", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11' # You can specify the Java version you want here

    - name: Build
      run: |
        mvn clean compile
